### PR TITLE
add okexchain walletconnect support

### PR DESCRIPTION
**Pull request by okexgithub**
We are the developers of okexchain. We have developed the corresponding code that supports okexchain based on the wallect connect protocol. Our code has added support for okexchain.
This includes the addition of resolution for OKT type signatures and transfer events.Usage examples are also included.
Please help merge, thank you.

### CODE REVIEW

**Review by okexgithub — COMMENTED** [review]
add okexchain support.

**Review by vikmeup — COMMENTED** [review]
Would it be possible to make it compatible with eth sign? seems like it's using the same params

**Comment by okexgithub** [comment]
> Would it be possible to make it compatible with eth sign? seems like it's using the same params

okexchain and eth are two chains, and there will be ambiguity if the eth sign is reused.okexchain's signature parameters are different from eth's.
bnb is also independent of eth in this project.So I think it's important to make a distinction.

**Comment by pedrouid** [comment]
I think this dedicated method would make sense given that messages are encoded differently

**Comment by vikmeup** [comment]
> I think this dedicated method would make sense given that messages are encoded differently

What's the current state of Wallet Core V2? Ideally we want to stay away from specific models and methods for each blockchain and make it as generic as possible. 

Otherwise it's gonna be a big pain to manage dozens of different blockchain models

**Pull request closed without merging**
